bar:
  height: 26
  location: top
  spacing: 5
  layer: bottom

  font: monospace:size=14

  foreground: ffffffff
  background: 000000ff

  left:
    - script:
        path: /usr/bin/dwl-status
        args: [/tmp/dwl.socket]
        anchors:
          - sel: &sel {foreground: 000000ff, deco: {background: { color: ffffffff }}}
          - occ: &occ {deco: {underline: { size: 3, color: ffffffff }}}
          - default: &default {foreground: ffffffff, deco: {stack: [{background: { color: 000000ff }}, {underline: { size: 0, color: ffffffff }}]}}
        content:
          list:
            right-spacing: 1
            items:
             - map:
                 conditions:
                   1_sel: {string: {text: " 1 ", <<: *sel}}
                   ~1_sel && 1_occ: {string: {text: " 1 ", <<: *occ}}
                   ~1_sel && ~1_occ: {string: {text: " 1 ", <<: *default}}
             - map:
                 conditions:
                   2_sel: {string: {text: " 2 ", <<: *sel}}
                   ~2_sel && 2_occ: {string: {text: " 2 ", <<: *occ}}
                   ~2_sel && ~2_occ: {string: {text: " 2 ", <<: *default}}
             - map:
                 conditions:
                   3_sel: {string: {text: " 3 ", <<: *sel}}
                   ~3_sel && 3_occ: {string: {text: " 3 ", <<: *occ}}
                   ~3_sel && ~3_occ: {string: {text: " 3 ", <<: *default}}
             - map:
                 conditions:
                   4_sel: {string: {text: " 4 ", <<: *sel}}
                   ~4_sel && 4_occ: {string: {text: " 4 ", <<: *occ}}
                   ~4_sel && ~4_occ: {string: {text: " 4 ", <<: *default}}
             - map:
                 conditions:
                   5_sel: {string: {text: " 5 ", <<: *sel}}
                   ~5_sel && 5_occ: {string: {text: " 5 ", <<: *occ}}
                   ~5_sel && ~5_occ: {string: {text: " 5 ", <<: *default}}
             - map:
                 conditions:
                   6_sel: {string: {text: " 6 ", <<: *sel}}
                   ~6_sel && 6_occ: {string: {text: " 6 ", <<: *occ}}
                   ~6_sel && ~6_occ: {string: {text: " 6 ", <<: *default}}
             - map:
                 conditions:
                   7_sel: {string: {text: " 7 ", <<: *sel}}
                   ~7_sel && 7_occ: {string: {text: " 7 ", <<: *occ}}
                   ~7_sel && ~7_occ: {string: {text: " 7 ", <<: *default}}
             - map:
                 conditions:
                   8_sel: {string: {text: " 8 ", <<: *sel}}
                   ~8_sel && 8_occ: {string: {text: " 8 ", <<: *occ}}
                   ~8_sel && ~8_occ: {string: {text: " 8 ", <<: *default}}
             - map:
                 conditions:
                   9_sel: {string: {text: " 9 ", <<: *sel}}
                   ~9_sel && 9_occ: {string: {text: " 9 ", <<: *occ}}
                   ~9_sel && ~9_occ: {string: {text: " 9 ", <<: *default}}
             - string: {text: " {layout} ", <<: *sel}
             - string: {text: " {title}", max: 74}
  right:
    - pipewire:
        content:
          map:
            on-click: defaultaudiomixer
            conditions:
              type == "sink":
                map:
                  conditions:
                    muted: {string: {text: "ğŸ”‡{linear_volume}%"}}
                    ~muted:
                      ramp:
                        tag: linear_volume
                        items:
                          - string: {text: "ğŸ”ˆ{linear_volume}%"}
                          - string: {text: "ğŸ”‰{linear_volume}%"}
                          - string: {text: "ğŸ”Š{linear_volume}%"}
    - script:
        path: /usr/bin/batmon
        content:
          map:
            on-click: batinfo
            conditions:
              charging: {string: {text: "ğŸ”Œ{capacity}%"}}
              ~charging:
                map:
                  conditions:
                    capacity == -1: {string: {text: ""}}
                    capacity >= 0 && capacity <= 20: {string: {text: "ğŸª«{capacity}%"}}
                    capacity > 20: {string: {text: "ğŸ”‹{capacity}%"}}
    - script:
        path: /usr/bin/netmon
        content:
          map:
            on-click: defaultconnect
            conditions:
              state == ready: {string: {text: "ğŸŒ{state}"}}
              state != ready: {string: {text: "ğŸš«{state}"}}
    - clock:
        time-format: "%Y-%m-%d"
        content:
          - string: {on-click: gsimplecal, text: "ğŸ“…{time}"}
    - clock:
        time-format: "%H:%M"
        content:
          - string: {on-click: gsimplecal, text: "â°{time}"}
    - label:
        content:
          string:
            on-click: logout_gui
            text: ğŸšª