bar:
  height: 26
  location: top
  spacing: 5
  layer: bottom

  font: monospace:pixelsize=14

  foreground: ffffffff
  background: 000000ff

  left:
    - script:
        path: /usr/bin/dwl-status
        args: [/tmp/dwl.socket]
        anchors:
          - sel: &sel {foreground: 000000ff, deco: {background: { color: ffffffff }}}
          - occ: &occ {deco: {underline: { size: 3, color: ffffffff }}}
          - default: &default {foreground: ffffffff, deco: {stack: [{background: { color: 000000ff }}, {underline: { size: 0, color: ffffffff }}]}}
        content:
          list:
            right-spacing: 1
            items:
             - map:
                 tag: 1_occ
                 values:
                   true:
                     map:
                       tag: 1_sel
                       values:
                         true: {string: {text: " 1 ", <<: *sel}}
                         false: {string: {text: " 1 ", <<: *occ}}
                   false:
                     map:
                       tag: 1_sel
                       values:
                         true: {string: {text: " 1 ", <<: *sel}}
                         false: {string: {text: " 1 ", <<: *default}}
             - map:
                 tag: 2_occ
                 values:
                   true:
                     map:
                       tag: 2_sel
                       values:
                         true: {string: {text: " 2 ", <<: *sel}}
                         false: {string: {text: " 2 ", <<: *occ}}
                   false:
                     map:
                       tag: 2_sel
                       values:
                         true: {string: {text: " 2 ", <<: *sel}}
                         false: {string: {text: " 2 ", <<: *default}}
             - map:
                 tag: 3_occ
                 values:
                   true:
                     map:
                       tag: 3_sel
                       values:
                         true: {string: {text: " 3 ", <<: *sel}}
                         false: {string: {text: " 3 ", <<: *occ}}
                   false:
                     map:
                       tag: 3_sel
                       values:
                         true: {string: {text: " 3 ", <<: *sel}}
                         false: {string: {text: " 3 ", <<: *default}}
             - map:
                 tag: 4_occ
                 values:
                   true:
                     map:
                       tag: 4_sel
                       values:
                         true: {string: {text: " 4 ", <<: *sel}}
                         false: {string: {text: " 4 ", <<: *occ}}
                   false:
                     map:
                       tag: 4_sel
                       values:
                         true: {string: {text: " 4 ", <<: *sel}}
                         false: {string: {text: " 4 ", <<: *default}}
             - map:
                 tag: 5_occ
                 values:
                   true:
                     map:
                       tag: 5_sel
                       values:
                         true: {string: {text: " 5 ", <<: *sel}}
                         false: {string: {text: " 5 ", <<: *occ}}
                   false:
                     map:
                       tag: 5_sel
                       values:
                         true: {string: {text: " 5 ", <<: *sel}}
                         false: {string: {text: " 5 ", <<: *default}}
             - map:
                 tag: 6_occ
                 values:
                   true:
                     map:
                       tag: 6_sel
                       values:
                         true: {string: {text: " 6 ", <<: *sel}}
                         false: {string: {text: " 6 ", <<: *occ}}
                   false:
                     map:
                       tag: 6_sel
                       values:
                         true: {string: {text: " 6 ", <<: *sel}}
                         false: {string: {text: " 6 ", <<: *default}}
             - map:
                 tag: 7_occ
                 values:
                   true:
                     map:
                       tag: 7_sel
                       values:
                         true: {string: {text: " 7 ", <<: *sel}}
                         false: {string: {text: " 7 ", <<: *occ}}
                   false:
                     map:
                       tag: 7_sel
                       values:
                         true: {string: {text: " 7 ", <<: *sel}}
                         false: {string: {text: " 7 ", <<: *default}}
             - map:
                 tag: 8_occ
                 values:
                   true:
                     map:
                       tag: 8_sel
                       values:
                         true: {string: {text: " 8 ", <<: *sel}}
                         false: {string: {text: " 8 ", <<: *occ}}
                   false:
                     map:
                       tag: 8_sel
                       values:
                         true: {string: {text: " 8 ", <<: *sel}}
                         false: {string: {text: " 8 ", <<: *default}}
             - map:
                 tag: 9_occ
                 values:
                   true:
                     map:
                       tag: 9_sel
                       values:
                         true: {string: {text: " 9 ", <<: *sel}}
                         false: {string: {text: " 9 ", <<: *occ}}
                   false:
                     map:
                       tag: 9_sel
                       values:
                         true: {string: {text: " 9 ", <<: *sel}}
                         false: {string: {text: " 9 ", <<: *default}}
             - string: {text: " {layout} ", <<: *sel}
             - string: {text: " {title}", max: 90}
  right:
    - alsa:
        card: default
        mixer: Master
        content:
          map:
            tag: online
            values:
              false: {string: {text: ðŸ”‡}}
              true:
                map:
                  on-click: defaultaudiomixer
                  tag: muted
                  values:
                    true: {string: {text: "ðŸ”‡{percent}%"}}
                    false:
                      ramp:
                        tag: volume
                        items:
                          - string: {text: "ðŸ”ˆ{percent}%"}
                          - string: {text: "ðŸ”‰{percent}%"}
                          - string: {text: "ðŸ”Š{percent}%"}
    - script:
        path: /usr/bin/batmon
        content:
          map:
            tag: capacity
            on-click: batinfo
            values:
              -1: {string: {text: ""}}
              0: {string: {text: "ðŸª«0%"}}
              1: {string: {text: "ðŸª«1%"}}
              2: {string: {text: "ðŸª«2%"}}
              3: {string: {text: "ðŸª«3%"}}
              4: {string: {text: "ðŸª«4%"}}
              5: {string: {text: "ðŸª«5%"}}
              6: {string: {text: "ðŸª«6%"}}
              7: {string: {text: "ðŸª«7%"}}
              8: {string: {text: "ðŸª«8%"}}
              9: {string: {text: "ðŸª«9%"}}
              10: {string: {text: "ðŸª«10%"}}
              11: {string: {text: "ðŸª«11%"}}
              12: {string: {text: "ðŸª«12%"}}
              13: {string: {text: "ðŸª«13%"}}
              14: {string: {text: "ðŸª«14%"}}
              15: {string: {text: "ðŸª«15%"}}
              16: {string: {text: "ðŸª«16%"}}
              17: {string: {text: "ðŸª«17%"}}
              18: {string: {text: "ðŸª«18%"}}
              19: {string: {text: "ðŸª«19%"}}
              20: {string: {text: "ðŸª«20%"}}
            default: {string: {text: "ðŸ”‹{capacity}%"}}
    - script:
        path: /usr/bin/netmon
        content:
          map:
            on-click: defaultconnect
            tag: state
            default: {string: {text: "ðŸš«{state}"}}
            values:
              ready: {string: {text: "ðŸŒ{state}"}}
    - clock:
        time-format: "%Y-%m-%d"
        content:
          - string: {on-click: gsimplecal, text: "ðŸ“…{time}"}
    - clock:
        time-format: "%H:%M"
        content:
          - string: {on-click: gsimplecal, text: "â°{time}"}
    - label:
        content:
          string:
            on-click: logout_gui
            text: ðŸšª