name: bullseye

on:
  push:
    branches:
      - c201-v2
      - testing
    paths:
      - 'woof-distro/arm/debian/bullseye/**'
      - 'woof-distro/x86_64/debian/bullseye/**'
      - 'woof-code/**'
      - 'merge2out'
      - 'ci/**'
      - '!**.svg'
      - '!**.png'
      - '!**.htm'
      - '!**.html'
  schedule:
    - cron: '0 0 * * 4'

jobs:
  x86_64-cros:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends vboot-kernel-utils cgpt extlinux qemu-system-x86 graphicsmagick-imagemagick-compat caca-utils
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources petbuild-cache petbuild-output kernel-kit-output
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-${{ github.job }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-local-repositories-
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
        sudo ln -s /usr/bin/mount /usr/local/bin/mount-FULL
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: |
        (echo 3; echo 1; echo 1; echo) | sudo -E ./merge2out
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_x86_64_debian_bullseye-cros
        sudo ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_x86_64_debian_bullseye-cros
        sudo ./1download
    - name: Get cached kernel-kit output
      id: get_kernel_kit_output_cache
      uses: actions/cache@v2
      with:
        path: kernel-kit-output
        key: ${{ github.workflow }}-${{ github.job }}-kernel-kit-output-${{ hashFiles('kernel-kit/**') }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-kernel-kit-output-
    - name: Move cached kernel-kit output
      run: sudo mv kernel-kit-output ../woof-out_x86_64_x86_64_debian_bullseye-cros/kernel-kit/output
    - name: Install ccache
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y --no-install-recommends ccache
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: Get cached ~/.ccache
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ github.workflow }}-${{ github.job }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-ccache-
    - name: kernel-kit
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      run: |
        cd ../woof-out_x86_64_x86_64_debian_bullseye-cros/kernel-kit
        sudo cp -f cros-build-x86_64.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_x86_64_debian_bullseye-cros
        echo | sudo ./2createpackages
    - name: Get cached petbuild-sources
      id: get_petbuild_sources_cache
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Get cached petbuild-cache
      id: get_petbuild_cache
      uses: actions/cache@v2
      with:
        path: petbuild-cache
        key: ${{ github.workflow }}-${{ github.job }}-petbuild-cache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-petbuild-cache-
    - name: Get cached petbuild-output
      id: get_petbuild_output_cache
      uses: actions/cache@v2
      with:
        path: petbuild-output
        key: ${{ github.workflow }}-${{ github.job }}-petbuild-output-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-petbuild-output-
    - name: 3builddistro
      run: |
        sudo chown -R root:root petbuild-output
        sudo mv petbuild-{sources,cache,output} ../woof-out_x86_64_x86_64_debian_bullseye-cros/
        cd ../woof-out_x86_64_x86_64_debian_bullseye-cros
        sudo -E ./3builddistro
    - name: Run automated tests
      run: |
        cd ci
        cp -f ../../woof-out_x86_64_x86_64_debian_bullseye/woof-output-bullseye-8.0/bullseye-8.0-ext4-2gb-legacy.img test.img
        ./test.sh test.img
    - name: Move cached directories
      run: |
        sudo mv ../woof-out_x86_64_x86_64_debian_bullseye-cros/petbuild-{sources,cache,output} .
        sudo mv ../woof-out_x86_64_x86_64_debian_bullseye-cros/kernel-kit/output kernel-kit-output
  arm-cros:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf vboot-kernel-utils u-boot-tools device-tree-compiler cgpt qemu-user-static binfmt-support
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources petbuild-cache petbuild-output kernel-kit-output
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-${{ github.job }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-local-repositories-
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
        sudo ln -s /usr/bin/mount /usr/local/bin/mount-FULL
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: |
        (echo 1; echo 1; echo; echo) | sudo -E ./merge2out
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye-cros
        sudo ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye-cros
        sudo ./1download
    - name: Get cached kernel-kit output
      id: get_kernel_kit_output_cache
      uses: actions/cache@v2
      with:
        path: kernel-kit-output
        key: ${{ github.workflow }}-${{ github.job }}-kernel-kit-output-${{ hashFiles('kernel-kit/**') }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-kernel-kit-output-
    - name: Move cached kernel-kit output
      run: sudo mv kernel-kit-output ../woof-out_x86_64_arm_debian_bullseye-cros/kernel-kit/output
    - name: Install ccache
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y --no-install-recommends ccache
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: Get cached ~/.ccache
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ github.workflow }}-${{ github.job }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-ccache-
    - name: kernel-kit
      if: steps.get_kernel_kit_output_cache.outputs.cache-hit != 'true'
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye-cros/kernel-kit
        sudo cp -f cros-build-arm.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye-cros
        echo | sudo ./2createpackages
    - name: Get cached petbuild-sources
      id: get_petbuild_sources_cache
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Get cached petbuild-cache
      id: get_petbuild_cache
      uses: actions/cache@v2
      with:
        path: petbuild-cache
        key: ${{ github.workflow }}-${{ github.job }}-petbuild-cache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-petbuild-cache-
    - name: Get cached petbuild-output
      id: get_petbuild_output_cache
      uses: actions/cache@v2
      with:
        path: petbuild-output
        key: ${{ github.workflow }}-${{ github.job }}-petbuild-output-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.job }}-petbuild-output-
    - name: 3builddistro
      run: |
        sudo chown -R root:root petbuild-output
        sudo mv petbuild-{sources,cache,output} ../woof-out_x86_64_arm_debian_bullseye-cros/
        cd ../woof-out_x86_64_arm_debian_bullseye-cros
        sudo -E ./3builddistro
    - name: Move cached directories
      run: |
        sudo mv ../woof-out_x86_64_arm_debian_bullseye-cros/petbuild-{sources,cache,output} .
        sudo mv ../woof-out_x86_64_arm_debian_bullseye-cros/kernel-kit/output kernel-kit-output