name: C201

on:
  push:
    branches:
      - c201-v2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf vboot-kernel-utils u-boot-tools device-tree-compiler
        curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o vercmp -
        sudo install -m 755 vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        mkdir -p local-repositories
        ln -s `pwd`/local-repositories ../local-repositories
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
    - name: Cache local-repositories
      id: cache-local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: local-repositories
    - name: Download packages
      run: |
        (echo 1; echo 1; echo; echo) | sudo -E ./merge2out
        cd ../woof-out_x86_64_arm_debian_bullseye
        sudo ./0setup
        sudo ./1download
    - name: Build kernel
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye/kernel-kit
        sudo cp -f c201-build.conf build.conf
        sudo ./build.sh
    - name: Build image
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye
        echo | sudo ./2createpackages
        sudo ./3builddistro