name: debian-bullseye

on:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            compat-distro-version: bullseye64
          - arch: x86
            compat-distro-version: bullseye
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: ${{ matrix.arch }}
      compat-distro: debian
      compat-distro-version: ${{ matrix.compat-distro-version }}
      kernel: debian-bullseye
      artifact: debian-${{ matrix.distro-compat-version }}-${{ github.run_number }}
      retention: 30
      runner: 'ubuntu-20.04'
