name: release

on:
  workflow_dispatch:
    branches:
      - testing
    inputs:
      name:
        description: 'Human-readable name'
        required: true
        default: 'Slacko64'
      version:
        description: 'Version number'
        required: true
        default: '8.0'
      suffix:
        description: 'Release name suffix, with leading -'
        required: false
        default: '-prepreprealpha1'
      arch:
        description: 'Architecture'
        required: false
        default: 'x86_64'
      compat-distro:
        description: 'Compatible distro'
        required: false
        default: 'slackware64'
      compat-distro-version:
        description: 'Compatible distro version'
        required: false
        default: '15.0'
      kernel:
        description: 'Kernel version'
        required: false
        default: '5.15.x'
      prefix:
        description: 'File name prefix'
        required: false
        default: 'slacko64'
      release:
        type: boolean
        description: 'Upload release draft'
        required: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}     
      name: ${{ github.event.inputs.name }}
      version: ${{ github.event.inputs.version }}
      arch: ${{ github.event.inputs.arch }}
      compat-distro: ${{ github.event.inputs.compat-distro }}
      compat-distro-version: ${{ github.event.inputs.compat-distro-version }}
      kernel: ${{ github.event.inputs.kernel }}
      prefix: ${{ github.event.inputs.prefix }}
      artifact: ${{ github.workflow }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.compat-distro }}-${{ github.event.inputs.compat-distro-version }}-${{ github.run_number }}
      retention: 1
  upload:
    needs: build
    if: github.event.inputs.release == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.workflow }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.compat-distro }}-${{ github.event.inputs.compat-distro-version }}-${{ github.run_number }}
          path: .
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.prefix }}-${{ github.event.inputs.version }}${{ github.event.inputs.suffix }}
          tag_name: ${{ github.event.inputs.prefix }}-${{ github.event.inputs.version }}${{ github.event.inputs.suffix }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
          draft: true
          prerelease: false
