name: slacko64-7

on:
  push:
    branches:
      - ci
      - testing
    paths:
      - 'woof-distro/x86_64/slackware64/14.2/**'
  pull_request:
    branches:
      - testing
    paths:
      - 'woof-distro/x86_64/slackware64/14.2/**'
  schedule:
    - cron: '0 0 1,14 * *'
  workflow_dispatch:
    branches:
      - ci
      - testing
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '7.1'
      suffix:
        description: 'Release name suffix, with leading -'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create cache directories
      run: |
        mkdir -p local-repositories petbuild-sources petbuild-cache petbuild-output
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-local-repositories-
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
        sudo ln -s bash /bin/ash
    - name: merge2out
      run: yes "" | sudo -E ./merge2out woof-distro/x86_64/slackware64/14.2
    - name: Set version
      if: github.event_name == 'workflow_dispatch'
      run: sudo sed -i s/^DISTRO_VERSION=.*/DISTRO_VERSION=${{ github.event.inputs.version }}/ ../woof-out_x86_64_x86_64_slackware64_14.2/DISTRO_SPECS
    - name: Set compression algorithm
      if: github.event_name != 'workflow_dispatch'
      run: |
        echo | sudo tee -a ../woof-out_x86_64_x86_64_slackware64_14.2/_00build.conf
        echo 'SFSCOMP="-comp lzo -Xalgorithm lzo1x_1"' | sudo tee -a ../woof-out_x86_64_x86_64_slackware64_14.2/_00build.conf
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        sudo -E ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        sudo -E ./1download
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        echo | sudo -E ./2createpackages
    - name: Get cached kernel-kit output
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: puppylinux-woof-CE/woof-CE
        branch: testing
        workflow: kernel-kit.yml
        workflow_conclusion: success
        name: kernel-kit-output-4.19.x-x86_64
        path: kernel-kit-output
    - name: Move cached kernel-kit output
      run: sudo mv kernel-kit-output ../woof-out_x86_64_x86_64_slackware64_14.2/kernel-kit/output
    - name: Get cached petbuild-sources
      uses: actions/cache@v2
      with:
        path: petbuild-sources
        key: ${{ github.workflow }}-petbuild-sources-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-sources-
    - name: Get cached petbuild-cache
      if: github.event_name != 'workflow_dispatch'
      uses: actions/cache@v2
      with:
        path: petbuild-cache
        key: ${{ github.workflow }}-petbuild-cache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-cache-
    - name: Get cached petbuild-output
      if: github.event_name != 'workflow_dispatch'
      uses: actions/cache@v2
      with:
        path: petbuild-output
        key: ${{ github.workflow }}-petbuild-output-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-petbuild-output-
    - name: Install cdrtools
      run: |
        [ -f local-repositories/mkisofs ] || (curl -L https://sourceforge.net/projects/cdrtools/files/alpha/cdrtools-3.02a09.tar.bz2/download | tar -xjf- && cd cdrtools-3.02 && make -j`nproc` && mv mkisofs/OBJ/x86_64-linux-cc/mkisofs ../local-repositories/mkisofs)
        sudo install -m 755 local-repositories/mkisofs /usr/local/bin/mkisofs
    - name: 3builddistro
      run: |
        sudo chown -R root:root petbuild-output
        sudo mv petbuild-{sources,cache,output} ../woof-out_x86_64_x86_64_slackware64_14.2/
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        sudo -E HOME=/root ./3builddistro
    - name: Create Release
      if: github.event_name == 'workflow_dispatch'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: slacko64-${{ github.event.inputs.version }}${{ github.event.inputs.suffix }}
        release_name: slacko64-${{ github.event.inputs.version }}${{ github.event.inputs.suffix }}
        draft: false
        prerelease: false
    - name: Upload ISO
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_slackware64_14.2/woof-output-slacko64-${{ github.event.inputs.version }}/slacko64-${{ github.event.inputs.version }}.iso
        asset_name: slacko64-${{ github.event.inputs.version }}.iso
        asset_content_type: application/octet-stream
    - name: Upload devx
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_slackware64_14.2/woof-output-slacko64-${{ github.event.inputs.version }}/devx_slacko64_${{ github.event.inputs.version }}.sfs
        asset_name: devx_slacko64_${{ github.event.inputs.version }}.sfs
        asset_content_type: application/octet-stream
    - name: Upload kernel sources
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ../woof-out_x86_64_x86_64_slackware64_14.2/kernel-kit/output/kernel_sources-4.19-kernel-kit.sfs
        asset_name: kernel_sources-4.19-kernel-kit.sfs
        asset_content_type: application/octet-stream
    - name: Move cached directories
      run: sudo mv ../woof-out_x86_64_x86_64_slackware64_14.2/petbuild-{sources,cache,output} .