name: slacko64

on:
  push:
    branches:
      - ci
      - testing

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends ccache
        ccache --set-config=hash_dir=false --set-config=max_size=2.0G
    - name: Create local-repositories
      run: |
        mkdir -p local-repositories
        ln -s `pwd`/local-repositories ../local-repositories
    - name: Get cached local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: ${{ github.workflow }}-local-repositories-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-local-repositories-
    - name: Install cdrtools
      run: |
        [ -f local-repositories/mkisofs ] || (curl -L https://sourceforge.net/projects/cdrtools/files/alpha/cdrtools-3.02a09.tar.bz2/download | tar -xjf- && cd cdrtools-3.02 && make -j`nproc` && mv mkisofs/OBJ/x86_64-linux-cc/mkisofs ../local-repositories/mkisofs)
        sudo install -m 755 local-repositories/mkisofs /usr/local/bin/mkisofs
    - name: Prepare build environment
      run: |
        [ -f local-repositories/vercmp ] || (curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o ../local-repositories/vercmp -)
        sudo install -m 755 local-repositories/vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: merge2out
      run: |
        (echo 3; echo 2; echo 3; echo; echo) | sudo -E ./merge2out
    - name: 0setup
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        sudo ./0setup
    - name: 1download
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        sudo ./1download
    - name: Get cached ~/.ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ github.workflow }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ github.workflow }}-ccache-
    - name: kernel-kit
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2/kernel-kit
        sudo cp -f slacko64-build.conf build.conf
        sudo -E ./build.sh
    - name: 2createpackages
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        echo | sudo ./2createpackages
    - name: 3builddistro
      run: |
        cd ../woof-out_x86_64_x86_64_slackware64_14.2
        sudo -E ./3builddistro